//! Driving the TPC-DS row generators, shared by the DAT and CSV outputs.
//!
//! Both outputs walk the generators identically — same row order, same seed
//! consumption — and differ only in how a chunk of rows is formatted into a
//! buffer. That difference is captured by [`RowFormat`]; everything else lives
//! here so the two formats cannot drift apart.
//!
//! Generation is parallel, using the same mechanism as the TPC-H text outputs:
//! each table is split into chunks of source rows
//! ([`TpcdsGenerationPlan`](super::plan::TpcdsGenerationPlan)), the chunks are
//! formatted into in memory buffers on separate threads, and a single writer
//! task appends the buffers to the output file in order (see
//! [`generate_file`]).

use super::runner::PlannedTable;
use crate::generate::{generate_file, Source};
use log::info;
use std::io;
use std::marker::PhantomData;
use std::ops::RangeInclusive;
use std::path::{Path, PathBuf};
use tpcdsgen::config::{Session, Table};
use tpcdsgen::row::*;

/// Return the output path for `table`'s file, following `tpchgen-cli`'s
/// `--parts`/`--part` naming convention:
///
/// When `--parts` was not requested creates a single `<table>.<ext>` file, otherwise
/// written into a subdirectory like `<table>/<table>.<chunk>.<ext>`.
///
/// Note that `--parts 1` is also written to a subdirectory.
///
/// This function creates the per-table subdirectory as needed.
pub(super) fn output_path(
    output_dir: &Path,
    table: Table,
    ext: &str,
    session: &Session,
) -> io::Result<PathBuf> {
    // sub directory `<table>/<table>.<chunk>.<ext>`
    if session.is_partitioned() {
        let dir = output_dir.join(table.get_name());
        std::fs::create_dir_all(&dir)?;
        Ok(dir.join(format!(
            "{}.{}.{ext}",
            table.get_name(),
            session.get_chunk_number()
        )))
    } else {
        // single `<table>.<ext>` file
        Ok(output_dir.join(format!("{}.{ext}", table.get_name())))
    }
}

/// A text output format for the TPC-DS row generators (DAT or CSV).
///
/// One instance formats every table, so implementations hold only the
/// format's options (such as the CSV delimiter), never per-table state.
pub(super) trait RowFormat: Clone + Send + 'static {
    /// The file extension of this format's output files.
    const EXTENSION: &'static str;

    /// Write the header line for `table` into `buffer`, if this format has
    /// one. Called exactly once per output file, before any rows.
    fn write_header(&self, table: Table, buffer: Vec<u8>) -> Vec<u8>;

    /// Format `rows` (all belonging to `table`) into `buffer`.
    fn write_rows<I>(&self, table: Table, rows: I, buffer: Vec<u8>) -> Vec<u8>
    where
        I: Iterator<Item = GeneratedRow>;
}

/// Trait for creating row generators.
pub(super) trait RowGeneratorFactory: RowGenerator + Sized {
    fn create() -> Self;
}

macro_rules! impl_factory {
    ($($gen:ty),*) => {
        $(
            impl RowGeneratorFactory for $gen {
                fn create() -> Self { Self::new() }
            }
        )*
    };
}

// Implement factory for all simple generators
impl_factory!(
    CallCenterRowGenerator,
    CatalogPageRowGenerator,
    CustomerRowGenerator,
    CustomerAddressRowGenerator,
    CustomerDemographicsRowGenerator,
    DateDimRowGenerator,
    DbgenVersionRowGenerator,
    HouseholdDemographicsRowGenerator,
    IncomeBandRowGenerator,
    InventoryRowGenerator,
    ItemRowGenerator,
    PromotionRowGenerator,
    ReasonRowGenerator,
    ShipModeRowGenerator,
    StoreRowGenerator,
    TimeDimRowGenerator,
    WarehouseRowGenerator,
    WebPageRowGenerator,
    WebSiteRowGenerator
);

// Implement factory for generators that emit sales and returns rows
impl_factory!(
    CatalogSalesRowGenerator,
    StoreSalesRowGenerator,
    WebSalesRowGenerator
);

/// Generate one planned table (one `--parts` chunk of one table) into
/// `output_dir`, using up to `num_threads` threads.
///
/// The returns tables are generated by their sales table's generator, which
/// emits rows for both tables; the rows of the other table are filtered out
/// (the same way the Arrow generators do).
pub(super) async fn generate_table<F: RowFormat>(
    format: F,
    output_dir: PathBuf,
    planned: PlannedTable,
    num_threads: usize,
) -> io::Result<()> {
    macro_rules! write_table {
        ($GENERATOR:ty) => {
            write_table::<F, $GENERATOR>(format, &output_dir, planned, num_threads).await
        };
    }

    match planned.table {
        // Simple tables: one row per source row
        Table::CallCenter => write_table!(CallCenterRowGenerator),
        Table::CatalogPage => write_table!(CatalogPageRowGenerator),
        Table::Customer => write_table!(CustomerRowGenerator),
        Table::CustomerAddress => write_table!(CustomerAddressRowGenerator),
        Table::CustomerDemographics => write_table!(CustomerDemographicsRowGenerator),
        Table::DateDim => write_table!(DateDimRowGenerator),
        Table::DbgenVersion => write_table!(DbgenVersionRowGenerator),
        Table::HouseholdDemographics => write_table!(HouseholdDemographicsRowGenerator),
        Table::IncomeBand => write_table!(IncomeBandRowGenerator),
        Table::Inventory => write_table!(InventoryRowGenerator),
        Table::Item => write_table!(ItemRowGenerator),
        Table::Promotion => write_table!(PromotionRowGenerator),
        Table::Reason => write_table!(ReasonRowGenerator),
        Table::ShipMode => write_table!(ShipModeRowGenerator),
        Table::Store => write_table!(StoreRowGenerator),
        Table::TimeDim => write_table!(TimeDimRowGenerator),
        Table::Warehouse => write_table!(WarehouseRowGenerator),
        Table::WebPage => write_table!(WebPageRowGenerator),
        Table::WebSite => write_table!(WebSiteRowGenerator),

        // Sales tables and the returns tables generated alongside them
        Table::CatalogSales | Table::CatalogReturns => write_table!(CatalogSalesRowGenerator),
        Table::StoreSales | Table::StoreReturns => write_table!(StoreSalesRowGenerator),
        Table::WebSales | Table::WebReturns => write_table!(WebSalesRowGenerator),

        // Source tables - skip
        _ => Ok(()),
    }
}

/// Write the rows of `planned.table` produced by the generator `G` to
/// `<table>.<ext>`, generating the chunks of the plan on up to `num_threads`
/// threads.
///
/// Progress is reported in chunks: the writer task advances by one per written
/// chunk (the totals are registered by
/// [`plan_tables`](super::runner::plan_tables)).
async fn write_table<F, G>(
    format: F,
    output_dir: &Path,
    planned: PlannedTable,
    num_threads: usize,
) -> io::Result<()>
where
    F: RowFormat,
    G: RowGeneratorFactory + Send + 'static,
{
    let PlannedTable {
        table,
        session,
        plan,
        progress,
    } = planned;

    let path = output_path(output_dir, table, F::EXTENSION, &session)?;
    info!("Writing {} using {num_threads} threads", path.display());

    let source_rows = session.get_scaling().get_row_count(table.source_table());
    let sources = plan.into_iter().map(move |range| RowSource::<F, G> {
        format: format.clone(),
        table,
        session: session.clone(),
        source_rows,
        range,
        generator: PhantomData,
    });

    generate_file(&path, sources, num_threads, progress.clone()).await?;
    progress.complete();

    info!("Generated {}", path.display());
    Ok(())
}

/// Generates the text for one chunk (a range of source rows) of one table.
struct RowSource<F, G> {
    format: F,
    /// The table to write; rows the generator emits for any other table are
    /// skipped
    table: Table,
    session: Session,
    /// Total source rows of the table, used to bound the last chunk
    source_rows: u64,
    /// The 1-based inclusive source rows of this chunk
    range: RangeInclusive<u64>,
    generator: PhantomData<G>,
}

impl<F, G> Source for RowSource<F, G>
where
    F: RowFormat,
    G: RowGeneratorFactory + Send + 'static,
{
    fn header(&self, buffer: Vec<u8>) -> Vec<u8> {
        self.format.write_header(self.table, buffer)
    }

    fn create(self, buffer: Vec<u8>) -> Vec<u8> {
        let Self {
            format,
            table,
            session,
            source_rows,
            range,
            ..
        } = self;

        let mut rows = RowIter::new(G::create(), session, source_rows);
        rows.set_source_row_range(*range.start(), *range.end());

        format.write_rows(table, rows.filter(|row| row.table() == table), buffer)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tpcds_cli::csv::Csv;
    use crate::tpcds_cli::dat::Dat;
    use tpcdsgen::config::{CompatMode, SessionBuilder};

    const CHUNK_BYTES: i64 = 8 * 1024 * 1024;

    /// Generate `table` in `format`, one chunk per range, concatenated in order
    fn chunked_bytes<F: RowFormat, G: RowGeneratorFactory + Send + 'static>(
        format: &F,
        table: Table,
        session: &Session,
        ranges: Vec<RangeInclusive<u64>>,
    ) -> Vec<u8> {
        let source_rows = session.get_scaling().get_row_count(table.source_table());
        let mut out = Vec::new();
        for range in ranges {
            let source = RowSource::<F, G> {
                format: format.clone(),
                table,
                session: session.clone(),
                source_rows,
                range,
                generator: PhantomData,
            };
            out.extend_from_slice(&source.create(Vec::new()));
        }
        out
    }

    fn session(scale_factor: f64) -> Session {
        SessionBuilder::new()
            .with_scale_factor(scale_factor)
            .build()
            .expect("session")
    }

    fn dat() -> Dat {
        Dat::new(PathBuf::from("."), CompatMode::Trino, CHUNK_BYTES).expect("dat output")
    }

    fn csv() -> Csv {
        Csv::new(PathBuf::from("."), ',', CHUNK_BYTES)
    }

    /// Splitting a table into chunks must produce exactly the same bytes as
    /// generating it in one pass: this is what makes parallel generation safe.
    #[test]
    fn chunks_concatenate_to_the_unchunked_output() {
        let session = session(1.0);
        let split = vec![1..=1, 2..=10, 11..=34, 35..=35];

        let whole =
            chunked_bytes::<_, ReasonRowGenerator>(&dat(), Table::Reason, &session, vec![1..=35]);
        let chunked =
            chunked_bytes::<_, ReasonRowGenerator>(&dat(), Table::Reason, &session, split.clone());
        assert!(!whole.is_empty());
        assert_eq!(whole, chunked);

        let whole =
            chunked_bytes::<_, ReasonRowGenerator>(&csv(), Table::Reason, &session, vec![1..=35]);
        let chunked =
            chunked_bytes::<_, ReasonRowGenerator>(&csv(), Table::Reason, &session, split);
        assert!(!whole.is_empty());
        assert_eq!(whole, chunked);
    }

    /// The sales generator emits rows for the sales and the returns table;
    /// each output file keeps only its own rows, in every chunk.
    #[test]
    fn sales_and_returns_are_generated_from_the_same_source_rows() {
        let session = session(0.01);
        let source_rows = session.get_scaling().get_row_count(Table::StoreSales);
        assert!(source_rows > 100);
        let split = vec![1..=(source_rows / 2), (source_rows / 2 + 1)..=source_rows];

        for table in [Table::StoreSales, Table::StoreReturns] {
            let whole = chunked_bytes::<_, StoreSalesRowGenerator>(
                &dat(),
                table,
                &session,
                vec![1..=source_rows],
            );
            let chunked =
                chunked_bytes::<_, StoreSalesRowGenerator>(&dat(), table, &session, split.clone());
            assert!(!whole.is_empty(), "{table} produced no rows");
            assert_eq!(whole, chunked, "{table} chunked output differs");
        }
    }

    /// An empty range (a table with no rows) produces no rows
    #[test]
    fn empty_range_produces_no_rows() {
        let session = session(1.0);
        #[allow(clippy::reversed_empty_ranges)]
        let empty =
            chunked_bytes::<_, ReasonRowGenerator>(&dat(), Table::Reason, &session, vec![1..=0]);
        assert!(empty.is_empty());
    }

    /// The header belongs to the file, not to a chunk: CSV writes one, DAT
    /// writes none, and neither depends on which chunk is first.
    #[test]
    fn header_is_written_by_the_format_not_the_chunk() {
        let dat_header = dat().write_header(Table::Reason, Vec::new());
        assert!(dat_header.is_empty(), "DAT output has no header");

        let csv_header = csv().write_header(Table::Reason, Vec::new());
        assert_eq!(
            String::from_utf8(csv_header).unwrap(),
            "r_reason_sk,r_reason_id,r_reason_desc\n"
        );
    }

    #[test]
    fn output_path_is_a_single_file_when_not_partitioned() {
        let path = output_path(Path::new("/tmp/out"), Table::Reason, "dat", &session(1.0)).unwrap();
        assert_eq!(path, PathBuf::from("/tmp/out/reason.dat"));
    }
}
