[package]
name = "tpchgen-arrow"
version = "3.0.0"
edition = "2024"
authors = ["clflushopt", "alamb"]
description = "TPC-H data generator into Apache Arrow format"
repository = { workspace = true }
readme = "README.md"
license = "Apache-2.0"

[dependencies]
arrow_59 = { workspace = true, optional = true }
arrow_60 = { workspace = true }
tpchgen = { path = "../tpchgen", version = "3.0.0" }

[features]
# Build against arrow 59 instead of the default arrow 60.
arrow_59 = ["dep:arrow_59"]

[dev-dependencies]
arrow_csv_59 = { workspace = true }
arrow_csv_60 = { workspace = true }
chrono = "0.4.39"
